### ISSUE TITLE
Spatiotemporal modeling

### ISSUE THREAD

**Issue by tea1528** [HolmesShuan/Compact-Global-Descriptor#1]
Hi, I am little bit confused about the implementation of CGD for spatiotemporal model. 

In the paper, it is stated that the weight is shared and the output of each frames is summed to get z. To do so, should I loop through all the frames and run AttentionLayer for every frames and sum all the output?

It would be greatly appreciated if you could elaborate more on spatiotemporal setting.

**Comment by HolmesShuan** [comment]
If I recall correctly, it can be implemented as
> loop through all the frames and run AttentionLayer for every frames and sum all the output.

Note that T dimension becomes smaller along with layer going deeper (see C2D in [Non-local networks](http://openaccess.thecvf.com/content_cvpr_2018/papers/Wang_Non-Local_Neural_Networks_CVPR_2018_paper.pdf)).

I will add my partner as a collaborator of this repo, if you have any further questions about spatiotemporal modeling. Thanks for your interest.


P.S. This work has not been accepted, yet.

**Comment by tea1528** [comment]
Thanks for the info!

**Comment by HolmesShuan** [comment]
@KeCh96 Any suggestions?

**Comment by KeCh96** [comment]
I did the video classification experiment in this paper. To save the computational cost, we average T frames, then compute the attention map. After that, the attention map is broadcasted to all frames. 

This process is a little different from the equation (12) in the paper. Equation (12) first compute the attention map of every frame then sum them up, while we first average the frames, then compute the attention map. This is a mistake when writing paper, and we will correct our paper soon. 

Thank you! @tea1528 

Our CGD code for video classification is as below:

```python
import numpy as np
import torch
from torch.autograd import Variable
import torch.nn as nn
from torch.utils.data import sampler
import math
import torch.nn.functional as F

class AttentionLayer(nn.Module):
    def __init__(self, in_channels, out_channels, bias=True, nonlinear=True):
        super(AttentionLayer, self).__init__()
        self.avg_pool = nn.AdaptiveAvgPool3d(1)
        self.max_pool = nn.AdaptiveMaxPool3d(1)
        self.softmax = nn.Softmax(dim=1)

        self.w0 = nn.Parameter(torch.ones(in_channels,1), requires_grad=True)
        self.w1 = nn.Parameter(torch.ones(in_channels,1), requires_grad=True)
        self.w2 = nn.Parameter(torch.ones(in_channels,1), requires_grad=True)
        
        self.bias0 = nn.Parameter(torch.zeros(1,in_channels,1,1,1), requires_grad=True)
        self.bias1 = nn.Parameter(torch.zeros(1,in_channels,1,1,1), requires_grad=True)
        self.bias2 = nn.Parameter(torch.zeros(1,in_channels,1,1,1), requires_grad=True)

        nn.init.xavier_uniform_(self.w0)
        nn.init.xavier_uniform_(self.w1)
        nn.init.xavier_uniform_(self.w2)


    def forward(self, x):
        b, c, _, _, _ = x.size()
        x0 = self.avg_pool(x).view(b, c,1,1,1)
        x1 = self.max_pool(x).view(b, c,1,1,1)
        
        x0_s = self.softmax(x0)

        y0 = torch.matmul(x0.view(b,c), self.w0).view(b, 1, 1, 1, 1)
        y1 = torch.matmul(x1.view(b,c), self.w1).view(b, 1, 1, 1, 1)

        y0_s = torch.tanh(y0*x0_s + self.bias0)
        y1_s = torch.tanh(y1*x0_s + self.bias1)

        y2 = torch.matmul(y1_s.view(b,c), self.w2).view(b, 1, 1, 1, 1)
        y2_s = torch.tanh(y2*y0_s + self.bias2).view(b, c, 1, 1, 1)

        z = x*(y2_s+1)
        return z
```
