### ISSUE TITLE
 Hello, I can't find your paper online. Can you send it to me?

### ISSUE THREAD

**Issue by xiaoweidao** [HolmesShuan/Compact-Global-Descriptor#2]
Hello, I can't find your paper online. Can you send it to me?

**Comment by xiaoweidao** [comment]
Compact Global Descriptor for Neural Networks

**Comment by HolmesShuan** [comment]
FYI.
https://arxiv.org/abs/1907.09665v3

**Comment by xiaoweidao** [comment]
> 供参考。 https://arxiv.org/abs/1907.09665v3


Thank you for your help
